/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(tnc_b1.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(73189f74b809d59a751fa00e5284f73c)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <tnc_nx/tnc_b1.h>
// pydoc.h is automatically generated in the build directory
#include <tnc_b1_pydoc.h>

void bind_tnc_b1(py::module& m)
{

    using tnc_b1    = ::gr::tnc_nx::tnc_b1;


    py::class_<tnc_b1, gr::block, gr::basic_block,
        std::shared_ptr<tnc_b1>>(m, "tnc_b1", D(tnc_b1))

        .def(py::init(&tnc_b1::make),
           D(tnc_b1,make)
        )
        



        ;




}








