/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(tnc.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(f4f6d1e99cb8a2dd1302f3431e2979b9)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <tnc_nx/tnc.h>
// pydoc.h is automatically generated in the build directory
#include <tnc_pydoc.h>

void bind_tnc(py::module& m)
{

    using tnc    = ::gr::tnc_nx::tnc;


    py::class_<tnc, gr::block, gr::basic_block,
        std::shared_ptr<tnc>>(m, "tnc", D(tnc))

        .def(py::init(&tnc::make),
           D(tnc,make)
        )
        



        ;




}








