/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(gos_encoder.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(9c82fd24bf232b40c714490c7fd45fa4)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/tnc_nx/gos_encoder.h>
// pydoc.h is automatically generated in the build directory
#include <gos_encoder_pydoc.h>

void bind_gos_encoder(py::module& m)
{

    using gos_encoder    = ::gr::tnc_nx::gos_encoder;


    py::class_<gos_encoder, gr::block, gr::basic_block,
        std::shared_ptr<gos_encoder>>(m, "gos_encoder", D(gos_encoder))

        .def(py::init(&gos_encoder::make),
           py::arg("is_tnc"),
           py::arg("sat_id"),
           D(gos_encoder,make)
        )
        



        ;




}








