/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(nx_encoder.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(228f2583b3f235a31b0826c6f0a38153)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/tnc_nx/nx_encoder.h>
// pydoc.h is automatically generated in the build directory
#include <nx_encoder_pydoc.h>

void bind_nx_encoder(py::module& m)
{

    using nx_encoder    = ::gr::tnc_nx::nx_encoder;


    py::class_<nx_encoder, gr::block, gr::basic_block,
        std::shared_ptr<nx_encoder>>(m, "nx_encoder", D(nx_encoder))

        .def(py::init(&nx_encoder::make),
           D(nx_encoder,make)
        )
        



        ;




}








